### ISSUE TITLE
Problems on Clozure CL

### ISSUE THREAD

**Issue by vityok** [scymtym/esrap#1]
There seems to be some weird problem with loading this library on Clozure CL. When loading a library that depends on `esrap` (via third libraries):
```
? (ql:quickload :cl-string-match)
To load "cl-string-match":
  Load 1 ASDF system:
    cl-string-match
; Loading "cl-string-match"
..................................................
[package esrap].............
> Error: Unknown type specifier: RESULT
> While executing: CCL::%%TYPEP, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
1 > 
```
but when loading `esrap` from the REPL:
```
? (ql:quickload :esrap)
To load "esrap":
  Load 1 ASDF system:
    esrap
; Loading "esrap"
..................................................
..
(:ESRAP)
```
and then libraries depending on `esrap` can be loaded without a problem as it gets "cached" after a successfull load.

This is very likely a problem with some `eval-when` block, but I didn't investigate it any further.

P.S. the Lisp is: `Clozure Common Lisp Version 1.11.5/v1.11.5  (LinuxX8632)`

**Comment by scymtym** [comment]
Thanks for the report.
