### ISSUE TITLE
SBCL hang when parsing deeply nested left-recursion rules

### ISSUE THREAD

**Issue by sheepduke** [scymtym/esrap#15]
First of all, I sincerely appreciate your work for maintaining this awesome library!

I wrote a small JSON parser using Esrap: https://github.com/sheepduke/esrap-json-parser

The rules were expressed in a left-recursive manner, translated from JSON RFC spec: https://datatracker.ietf.org/doc/html/rfc7159

Everything worked like a charm. However, when parsing large JSON files, like this one (https://github.com/json-iterator/test-data/blob/master/large-file.json), the SBCL would hang.

My guess is that the left recursion nested so deep that Esrap failed to handle it.

Could you please provide more clues?

**Comment by scymtym** [comment]
Thank you for the report. I didn't have time to look into it, yet. I will try to do that in the next days.

**Comment by scymtym** [comment]
I tried the provided grammar and input file and the hanging is likely SBCL running out of memory and terminating (check `*inferior-lisp*` buffer if you are using SLIME).

The foremost underlying problem is that ESRAP stores intermediate parse results in a cache which requires a lot of memory. This can mitigated to some extend by writing the grammar in a certain way but not entirely. I tried to apply such tricks to the provided grammar (at the end of this comment). This reduces the memory usage but enough to be practical. The following succeeds only with a 16 GB dynamic space:
```cl
(let ((esrap:*on-left-recursion* :error))
  (esrap:parse 'json:json (alexandria:read-file-into-string "/tmp/large-file.json") :raw t))
```
Mind that `:raw t` disables the construction of the instances defined in `models.lisp` because that would blow the heap.

Sadly, I'm not sure what could be done about this. If possible, feeding smaller chunks of JSON to the parser might work. Otherwise switching to a different JSON parser seems like the only option, sorry.

Here is the slightly improved grammar. The main principles are
* Avoid the cache to keep fewer intermediate results in memory
* Inline trivial rules into "callers" to avoid intermediate rules
* Add lookahead to avoid rule calls where possible

```cl
(defpackage json
  (:use #:cl
        #:esrap
        #:models)
  (:export #:json))

(in-package json)

(defrule json (and ws value ws)
  (:function second))

(defrule value
    (or "false"
        "true"
        "null"
        object-or-array
        number
        string)
  (:use-cache nil))

(defrule object-or-array
    (and ws
         (or (and (& #\{) object)
             (and (& #\[) array))
         ws)
  (:function second)
  (:function second)
  (:use-cache nil))

(defrule object
    (and (and #\{ ws) ; begin-object
         (? (and member (* additional-member)))
         (and ws #\})) ; end-object
  (:function second)
  (:destructure (&optional first-member additional-members)
    (make-instance 'json-object
                   :members (when first-member
                              (list* first-member additional-members))))
  (:use-cache nil))

(defrule additional-member
    (and ws #\, ws member)
  (:function fourth)
  (:use-cache nil))

(defrule member
    (and string ws #\: ws value)
  (:destructure (key ws1 name-separator ws2 value)
    (declare (ignore ws1 name-separator ws2))
    (make-instance 'json-kv-pair :key key :value value))
  (:use-cache nil))

(defrule array
    (and (and #\[ ws) ; begin-array
         (? (and value (* additional-element)))
         (and ws #\])) ; end-array
  (:function second)
  (:destructure (&optional first-element additional-elements)
    (make-instance 'json-array
                   :members (when first-element
                              (list* first-element additional-elements))))
  (:use-cache nil))

(defrule additional-element
    (and ws #\, ws value)
  (:function fourth)
  (:use-cache nil))

(defrule number
    (and (? #\-)
         int
         (? frac)
         (? exp))
  (:text t)
  (:lambda (text)
    (let ((*read-default-float-format* config:*float-precision*))
      (parse-number:parse-number text)))
  (:use-cache nil))

(defrule int
    (or #\0
        (and positive-digit (* digit)))
  (:text t)
  (:use-cache nil))

(defrule frac
    (and #\. (+ digit))
  (:text t)
  (:use-cache nil))

(defrule exp
    (and (or #\e #\E)
         (? (or #\- #\+))
         (+ digit))
  (:text t)
  (:use-cache nil))

(defrule string
    (and #\" (* char) #\")
  (:function second)
  (:lambda (chars)
    (coerce chars 'string))
  (:use-cache nil)) ; TEST

(defun unescaped-p (char)
  (let ((code (char-code char)))
    (or (<= #x20 code #x21)
        (<= #x23 code #x5B)
        (<= #x5D code #x10FFFF))))

(defrule char
    (or (and (& #\\) escaped)
        (and (and) (unescaped-p character)))
  (:function second)
  (:use-cache nil))

(defrule escaped
    (or escaped-quotation-mark
        escaped-backslash
        escaped-slash
        escaped-backspace
        escaped-form-feed
        escaped-line-feed
        escaped-carriage-return
        escaped-tab
        escaped-utf8
        escaped-utf16)
  (:use-cache nil))

(defrule escaped-quotation-mark "\\\""
  (:constant #\")
  (:use-cache nil))

(defrule escaped-backslash "\\\\"
  (:constant #\\)
  (:use-cache nil))

(defrule escaped-slash "\\/"
  (:constant #\/)
  (:use-cache nil))

(defrule escaped-backspace "\\b"
  (:constant #\backspace)
  (:use-cache nil))

(defrule escaped-form-feed "\\f"
  (:constant #\page)
  (:use-cache nil))

(defrule escaped-line-feed "\\n"
  (:constant #\newline)
  (:use-cache nil))

(defrule escaped-carriage-return "\\r"
  (:constant #\return)
  (:use-cache nil))

(defrule escaped-tab "\\t"
  (:constant #\tab)
  (:use-cache nil))

(defun basic-multilingual-plane-p (text)
  (let ((code (parse-integer text :start 2 :radix 16)))
    (or (<= #x0000 code #x007F)
        (<= #x0080 code #x07FF)
        (<= #x0800 code #x0FFF)
        (<= #x1000 code #xCFFF)
        (<= #xD000 code #xD7FF)
        (<= #xE000 code #xFFFF))))

(defrule escaped-utf8 (basic-multilingual-plane-p escaped-unicode)
  (:text t)
  (:lambda (text)
    (let ((code (parse-integer text :start 2 :radix 16)))
      (code-char code))))

(defun extended-multilingual-plane-p (text)
  (let ((code (parse-integer text :start 2 :end 6 :radix 16)))
    (print code)
    (<= #xD800 code #xDBFF)))

(defrule escaped-utf16 (extended-multilingual-plane-p escaped-two-unicodes)
  (:lambda (text)
    (let* ((code1 (parse-integer text :start 2 :end 6 :radix 16))
           (code2 (parse-integer text :start 8 :end 12 :radix 16)))
      (code-char (logior #x10000
                         (ash (logand code1 #x3FF) 10)
                         (logand code2 #x3FF))))))

(defrule escaped-two-unicodes (and escaped-unicode escaped-unicode)
  (:text t))

(defrule escaped-unicode (and "\\u" hex hex hex hex)
  (:text t))

(defrule unescaped
    (unescaped-p character)
  (:use-cache nil))

(defrule ws
    (* (character-ranges #\space #\tab #\newline #\return))
  (:constant nil)
  (:use-cache nil))

(defrule positive-digit
    (character-ranges (#\1 #\9))
  (:use-cache nil))

(defrule hex (or (character-ranges (#\a #\f))
                 (character-ranges (#\A #\F))
                 digit)
  (:use-cache nil))

(defrule digit (character-ranges (#\0 #\9))
  (:use-cache nil))
```

**Comment by sheepduke** [comment]
Such an informative reply! I really appreciate it! 

I carefully studied your example and I think I understood your optimization rules. There are still a few points that I do not fully understand:

1. I thought the cache is a technique to exchanging time with space. So by providing `(:use-cache nil)`, the parser will run slower, right?
2. When multiple `(:function xxx)` expressions are provided, they will be executed sequentially in a chain, right? What is its performance compared to `(:destructive)`?
3. I noticed that you were using `second` etc as a terminal function, but the doc did not cover this part. Is it possible to update it there?
4. Are there any other performance related tips? It would be really nice if these can be written in the doc as well. They are very helpful!
5. In this case, does ESRAP still work in linear time? I read the doc, but I am a bit curious about this part...

Again, really thank you for your help!

**Comment by scymtym** [comment]
> 1. I thought the cache is a technique to exchanging time with space. So by providing `(:use-cache nil)`, the parser will run slower, right?

Not necessarily. Constructing cache entries and putting those into the cache also consumes times (and, more importantly, space). I also  suspect that the cache is not really used in this case since JSON seems to be parsable with a single-character lookahead.

> 2. When multiple `(:function xxx)` expressions are provided, they will be executed sequentially in a chain, right? What is its performance compared to `(:destructive)`?

`:function` should generally be faster. One reason is that `:destructure` uses `destructuring-bind` and thus verifies the structure (including ignored parts). Using `:function` also allows Esrap to know that certain parts of the parse result produced by the expression will not be used. This information can be used for optimizations.

> 3. I noticed that you were using `second` etc as a terminal function, but the doc did not cover this part. Is it possible to update it there?

Not sure what you mean. A terminal function would be part of the expression, but I think I only used `(:function second)`.
 
> 4. Are there any other performance related tips? It would be really nice if these can be written in the doc as well. They are very helpful!

Nothing I can think of right now.

> 5. In this case, does ESRAP still work in linear time? I read the doc, but I am a bit curious about this part...

Time is really not the main issue here, space is. In my experiment, parsing the "large" file was only possible with a heap size of 16 GB and most of the execution time was due to garbage collection. This is because Esrap, even without the cache, allocates lots of intermediate parse results. The above tricks cut down on the amount of such intermediate results, but not enough to make the parser practical.

**Comment by sheepduke** [comment]
>> 3. noticed that you were using second etc as a terminal function, but the doc did not cover this part. Is it possible to update it there?
>
> Not sure what you mean. A terminal function would be part of the expression, but I think I only used (:function second).

I mean the doc describes:

> A function terminal succeeds if either
> 1. function-name returns T as its third value.
> 2. function-name returns nil as its third value (or returns only two values) and nil as its second value. This indicates that the entire remaining input has been consumed.
> 3. function-name returns nil as its third value (or returns only two values) and an integer > position as its second value indicating the position up to which text has been consumed.
> 4. function-name returns a value of type successful-parse as its first value. 

I am confused because `second` does not satisfy this statement...

**Comment by scymtym** [comment]
A function terminal means using `(function SOME-FUNCTION)` in an expression while I used `second` in the "options" part of a rule definition. Maybe showing both at the same time makes the difference clear:

```cl
(defrule foo
    (and "something" (function SOME-FUNCTION))
  (:function second))
```

**Comment by sheepduke** [comment]
New lesson learned! I will close this issue then. 

Thank you for helping out! :-D

**Comment by sheepduke** [comment]
gg
