### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by MIvanchev** [scymtym/esrap#21]
Thank you for this great library! I just released a parser for PulseAudio's pacmd tool (https://github.com/MIvanchev/cl-pacmd-parser) based on it and it's working great. I wanted to suggest maybe releasing and tagging a new version since a lot has happened since 2019 :) Keep up the good work!

**Comment by scymtym** [comment]
Sure, why not.

**Comment by MIvanchev** [comment]
Sorry to nag again @scymtym but could you also tag it 🤭

**Comment by scymtym** [comment]
I think I did. https://github.com/scymtym/esrap/releases/tag/release-0.18 contains all commits except the one that bumps the version for the next "release".

**Comment by MIvanchev** [comment]
Ah, OK, that's the next release, great, thanks.
