### ISSUE TITLE
Transform example in README predates new caching behaviour

### ISSUE THREAD

**Issue by fb08af68** [scymtym/esrap#5]
The README contains two example of setting a transform via creating a `rule` instance and via `defrule`. Right now the two code snippets will behave in a noticeably different way, because only the `defrule` version will have caching (which was previously the default behaviour for all rules).

**Comment by scymtym** [comment]
Thank you for pointing this out.

I will probably make rules created with `make-instance` more similar to ones created with `defrule` by default. I'm also thinking about emphasizing `defrule` more in the README.
